/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IM4mDAOInterface extends utils.Interface {
  contractName: "IM4mDAO";
  functions: {
    "convertRecord(uint256,address,address,uint256)": FunctionFragment;
    "convertToM4mNFT(address,uint256)": FunctionFragment;
    "convertibleList(address)": FunctionFragment;
    "m4mNFT()": FunctionFragment;
    "redeem(uint256,address,uint256)": FunctionFragment;
    "setConvertibleList(address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "convertRecord",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToM4mNFT",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertibleList",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "m4mNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setConvertibleList",
    values: [string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "convertRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToM4mNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertibleList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "m4mNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setConvertibleList",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IM4mDAO extends BaseContract {
  contractName: "IM4mDAO";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IM4mDAOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    convertRecord(
      m4mTokenId: BigNumberish,
      user: string,
      nft: string,
      originalTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    convertToM4mNFT(
      origin: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    convertibleList(nft: string, overrides?: CallOverrides): Promise<[boolean]>;

    m4mNFT(overrides?: CallOverrides): Promise<[string]>;

    redeem(
      m4mTokenId: BigNumberish,
      origin: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setConvertibleList(
      nft: string,
      enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  convertRecord(
    m4mTokenId: BigNumberish,
    user: string,
    nft: string,
    originalTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  convertToM4mNFT(
    origin: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  convertibleList(nft: string, overrides?: CallOverrides): Promise<boolean>;

  m4mNFT(overrides?: CallOverrides): Promise<string>;

  redeem(
    m4mTokenId: BigNumberish,
    origin: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setConvertibleList(
    nft: string,
    enabled: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    convertRecord(
      m4mTokenId: BigNumberish,
      user: string,
      nft: string,
      originalTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    convertToM4mNFT(
      origin: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    convertibleList(nft: string, overrides?: CallOverrides): Promise<boolean>;

    m4mNFT(overrides?: CallOverrides): Promise<string>;

    redeem(
      m4mTokenId: BigNumberish,
      origin: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setConvertibleList(
      nft: string,
      enabled: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    convertRecord(
      m4mTokenId: BigNumberish,
      user: string,
      nft: string,
      originalTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertToM4mNFT(
      origin: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    convertibleList(nft: string, overrides?: CallOverrides): Promise<BigNumber>;

    m4mNFT(overrides?: CallOverrides): Promise<BigNumber>;

    redeem(
      m4mTokenId: BigNumberish,
      origin: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setConvertibleList(
      nft: string,
      enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    convertRecord(
      m4mTokenId: BigNumberish,
      user: string,
      nft: string,
      originalTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertToM4mNFT(
      origin: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    convertibleList(
      nft: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    m4mNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeem(
      m4mTokenId: BigNumberish,
      origin: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setConvertibleList(
      nft: string,
      enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
